config/routes.rb
Rails.application.routes.draw do
  resources :urls, path: '', only: [:index, :create, :show]
  resources :visitors, only: :show
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/url.rb
BASE = 36

class Url < ApplicationRecord
  validates :full_url, url: { allow_nil: false, allow_blank: false }
  has_many :visitors

  def code
    id.to_s(BASE) if id?
  end

  def self.find_by_code(code)
    self.find(code.to_i(BASE))
  end

  def to_param
    code
  end
end

app/models/visitor.rb
class Visitor < ApplicationRecord
  before_save :parse_user_agent

  def self.from(req)
    Visitor.new(
        ip: req.remote_ip,
        user_agent: req.headers['User-Agent'],
        referer: req.headers['Referer']
    )
  end

  private

  def parse_user_agent
    data = UserAgent.parse(user_agent)
    self.browser_name = data.browser
    self.browser_version = data.version
  rescue
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/urls_controller.rb
class UrlsController < ApplicationController
  after_action :store_visitor, only: :show

  def index
    @url = Url.new
  end

  def create
    @url = Url.new(url_params)
    if @url.save
      render :create
    else
      render :index
    end
  end

  def show
    @url = Url.find_by_code(params[:id])
    redirect_to @url.full_url
  rescue ActiveRecord::RecordNotFound
    head :not_found
  end

  private

  def url_params
    params.require(:url).permit(:full_url)
  end

  def store_visitor
    @url.visitors << Visitor.from(request) unless @url.nil?
  end
end

app/controllers/visitors_controller.rb
class VisitorsController < ApplicationController
  def show
    @visitors = VisitorsViewModel.new(Url.find_by_code(params[:id]))
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/urls_helper.rb
module UrlsHelper
end

app/helpers/visitors_helper.rb
module VisitorsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ShortUrl</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <nav class="navbar navbar-expand-md navbar-dark bg-dark fixed-top">
      <%= link_to 'Short url', urls_path, class: 'navbar-brand' %>
    </nav>
    <div class="container">
      <%= yield %>
    </div>
  </body>
</html>

app/views/urls/_errors.html.erb
<% if target.errors.any? %>
  <div class="alert alert-danger">
    <ul>
      <% target.errors.messages.each do |_, msg| %>
        <li><%= msg.join(', ') %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/urls/create.html.erb
<div class="alert alert-success">
  Here is your short url:
</div>

<div class="card">
  <div class="card-body">
    <%= polymorphic_url(@url, only_path: false) %>
  </div>
</div>

app/views/urls/index.html.erb
<div class="alert alert-secondary">
  Allows http or https urls, ex: http://google.com or https://en.wikipedia.org/
</div>

<%= form_for :url do |f| %>
  <%= render 'errors', target: @url %>
  <div class="form-group">
    <%= f.label :full_url, 'URL' %>
    <%= f.text_field :full_url, class: 'form-control' %><br />
  </div>

  <%= f.submit 'Get short url', class: 'btn btn-primary' %>
<% end %>

app/views/visitors/_table.html.erb
<table class="table">
  <thead>
    <tr>
      <th scope="col"><%= field.humanize %></th>
      <th scope="col">#</th>
    </tr>
  </thead>
  <tbody>
    <% collection.each do |visitor| %>
      <tr>
        <td><%= visitor.attributes[field] || 'Unknown' %></td>
        <td><%= visitor.count %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/visitors/show.html.erb
<div class="card">
  <div class="card-body">
    <%= polymorphic_url(@visitors.url, only_path: false) %>
  </div>
</div>
<br/>

<h3>Top referers</h3>
<%= render 'table', collection: @visitors.top_referers, field: 'referer' %>

<h3>Top browsers</h3>
<%= render 'table', collection: @visitors.top_browsers, field: 'browser_name' %>